"use client";

import { useEffect, useState } from "react";
import Link from "next/link";

const PHRASES = [
  "Make me a full 4-year CS plan",
      "What CS courses have the highest average GPA?",
      "Easiest Gen Ed for the natural world requirement?",
      "What are the prerequisites for CS 251?",
      "Hardest courses at UIC by GPA?",
      "Best electives for a CS major?",
      "What classes should I take my first semester as a CS major?",
      "What are the easiest 200-level CS courses at UIC?",
      "What are the hardest CS classes at UIC?",
      "What math classes do CS majors need at UIC?",
      "How hard is CS 211 compared to CS 141?",
      "How hard is CS 251 compared to CS 211?",
      "What classes are best if I want to become a data analyst?",
      "What classes are best if I want to become a software engineer?",
      "What UIC courses help with web development?",
      "What UIC classes help with cybersecurity?",
      "What are the easiest science Gen Eds at UIC?",
      "What are the easiest humanities Gen Eds at UIC?",
      "What are the best GPA booster classes at UIC?",
      "What are the easiest business electives at UIC?",
      "Which CS classes have the best average grades?",
      "Can you build me a 4-year pre med plan at UIC?",
      "Can you build me a 4-year engineering plan at UIC?",
      "Can you build me a 4-year business plan at UIC?",
      "Who gives the best grades in MATH 180?",
      "Best rated CS professors at UIC?",
      "Easiest professor for CHEM 122?",
      "Which professors give the most As in calculus?",
      "Best biology professors at UIC?",
      "Who teaches CS 211 and how are they?",
      "Who is the easiest professor for MATH 121?",
      "Who is the best professor for CS 141?",
      "Who is the best professor for CS 211?",
      "Who is the best professor for CS 251?",
      "Who is the easiest professor for ENGL 160?",
      "Which professors are hardest graders at UIC?",
      "Which professors are the most liked by students?",
      "Which professors are best for freshmen?",
      "Which professors are easiest for science Gen Eds?",
      "Who is the best professor for MATH 181?",
      "Who is the best professor for CHEM 122?",
      "Who is the best professor for BIOS 110?",
      "Who is the best professor for ECON 120?",
      "Who is the best professor for ACTG 210?",
      "Which professors are best for pre med students?",
      "Which professors are best for business majors?",
      "Which professors are best for engineering students?",
      "Which UIC professors are easiest overall?",
      "Which UIC professors are hardest overall?",
      "Which professors are known for being fair graders?",
      "Which professors have the highest ratings and high GPA averages?",
      "Can you rank the best professors for calculus at UIC?",
      "Can you rank the best professors for CS at UIC?",
      "Who is the best professor at UIC for GPA and learning balance?",
      "How much is UIC tuition in-state?",
      "Do I qualify for the Aspire Grant?",
      "When is my fall tuition bill due?",
      "What scholarships can I apply for?",
      "How does UIC compare to UIUC in cost?",
      "What is the Aspire Grant and who qualifies?",
      "How much is UIC tuition out of state?",
      "How much does UIC cost per semester?",
      "How much does it cost to live on campus at UIC?",
      "How much do dorms cost at UIC?",
      "How much is a meal plan at UIC?",
      "What does UIC usually cost after aid?",
      "How much are student fees at UIC?",
      "How much does UIC cost for international students?",
      "What is the cheapest way to attend UIC?",
      "What scholarships are easiest to get at UIC?",
      "Does UIC give merit scholarships?",
      "What is the difference between tuition and total cost of attendance?",
      "Can I pay tuition monthly at UIC?",
      "What happens if I miss a tuition payment?",
      "What is included in the cost of attendance at UIC?",
      "Is UIC affordable compared to DePaul?",
      "Is UIC affordable compared to UIUC?",
      "How much debt do UIC students usually graduate with?",
      "What grants are available for Illinois students at UIC?",
      "Does UIC offer emergency grants?",
      "Are there scholarships for transfer students?",
      "Are there scholarships for international students?",
      "What financial aid is available for first year students?",
      "How expensive is parking at UIC?",
      "Does UIC charge different tuition by major?",
      "Can you compare UIC cost for living on campus versus commuting?",
      "Best dorm for a freshman engineering student?",
      "Should I live on campus or off campus?",
      "Which dorms don't require a meal plan?",
      "Cheapest housing options at UIC?",
      "What LLCs are available in JST?",
      "What's the difference between ARC and JST?",
      "What is the best dorm at UIC for freshmen?",
      "What is the quietest dorm at UIC?",
      "Which UIC dorm is the most social?",
      "Which UIC dorm is best for engineering students?",
      "Which UIC dorm is best for pre med students?",
      "Which UIC dorm is closest to classes?",
      "Which dorm has the best food access?",
      "Which dorm is best for international students?",
      "Which dorm is best for transfer students?",
      "What housing should a commuter student consider?",
      "Should I choose ARC, JST, MRH, or SSR?",
      "What are the pros and cons of living at ARC?",
      "What are the pros and cons of living at JST?",
      "What are the pros and cons of living off campus near UIC?",
      "How much does off campus housing near UIC usually cost?",
      "What neighborhoods are popular for UIC students?",
      "Is Little Italy a good place to live for UIC students?",
      "Is Pilsen a good place to live for UIC students?",
      "Can freshmen live off campus at UIC?",
      "Which dorms have kitchens at UIC?",
      "Which dorms have private bathrooms at UIC?",
      "Which dorms require a meal plan?",
      "Which dorms are apartment style at UIC?",
      "When does UIC housing open?",
      "How do I apply for UIC housing?",
      "How do I choose a roommate at UIC?",
      "What is the best housing option for a CS student?",
      "What is the cheapest dorm that still feels nice?",
      "Can you compare ARC and JST for me?",
      "Can you compare living on campus versus commuting to UIC?",
      "What is the best overall housing choice at UIC?",
      "What frats and sororities are at UIC?",
      "How does Greek rush work at UIC?",
      "Best clubs for pre-med students?",
      "What is the Spark Festival?",
      "What is the Involvement Fair?",
      "Best student orgs for CS majors?",
      "What is UIC student life like?",
      "What clubs should a freshman join at UIC?",
      "What clubs are best for making friends at UIC?",
      "What are the most popular student organizations at UIC?",
      "What events happen during welcome week at UIC?",
      "What is homecoming like at UIC?",
      "How do I meet people at UIC as a commuter?",
      "How do I make friends fast at UIC?",
      "What is Greek life like at UIC?",
      "What clubs are best for business students?",
      "What clubs are best for engineering students?",
      "What clubs are best for international students?",
      "What clubs are best for transfer students?",
      "What clubs are best for pre law students?",
      "What are the best volunteering clubs at UIC?",
      "What are the best leadership opportunities at UIC?",
      "How do I join student government at UIC?",
      "How do I find student events at UIC?",
      "What are the best fun events at UIC?",
      "What are the best cultural organizations at UIC?",
      "What are the best clubs for meeting ambitious people at UIC?",
      "What are the best clubs for CS majors at UIC?",
      "What are the best clubs for pre med students at UIC?",
      "What are the best clubs for finance students at UIC?",
      "What should I do my first month at UIC?",
      "How can I get involved fast at UIC?",
      "What organizations help with networking at UIC?",
      "What organizations help with community service at UIC?",
      "What are the biggest student events each semester at UIC?",
      "Can you suggest the best student orgs for my major at UIC?",
      "Can you help me build a campus involvement plan at UIC?",
      "What dining options are open late?",
      "Is there 24-hour food on campus?",
      "Which meal plan is best for freshmen?",
      "Where is the cheapest food near UIC?",
      "What halal food options are on campus?",
      "What are the hours for 605 Commons?",
      "What meal plan should I buy at UIC?",
      "Is the UIC meal plan worth it?",
      "Where can I get healthy food at UIC?",
      "Where can I get halal food near UIC?",
      "Where can I get vegetarian food at UIC?",
      "Where can I get vegan food at UIC?",
      "Where can I get coffee on campus at UIC?",
      "What restaurants are closest to UIC?",
      "What is open early in the morning at UIC?",
      "What is open late at night near UIC?",
      "Where can I eat between classes at UIC?",
      "Where can commuters eat at UIC?",
      "Are there microwaves on campus at UIC?",
      "What are the meal swipe options at UIC?",
      "How does dining dollars work at UIC?",
      "Can I use meal swipes at all campus locations?",
      "Which meal plan gives the most value at UIC?",
      "What are the hours for campus dining at UIC?",
      "Is there good breakfast on campus at UIC?",
      "Where can I get snacks on campus at UIC?",
      "Do UIC dining locations have allergy friendly options?",
      "What should freshmen know about meal plans at UIC?",
      "Can commuters buy meal plans at UIC?",
      "What food options are open on weekends at UIC?",
      "Where can I eat on east campus?",
      "Where can I eat on west campus?",
      "What is the best meal plan for someone who eats on campus a lot?",
      "What is the best meal plan for someone who goes home often?",
      "Can you compare UIC meal plans for me?",
      "What are the best food choices at UIC for saving money?",
      "How do I get free student tickets?",
      "What conference is UIC in?",
      "Where is the basketball arena?",
      "What is the Flames Fast Pass?",
      "What's the UIC basketball Instagram?",
      "How do UIC student tickets work?",
      "Is UIC Division 1?",
      "What sports does UIC have?",
      "Where do UIC basketball games happen?",
      "Where do UIC volleyball games happen?",
      "Where do UIC soccer games happen?",
      "What conference is UIC basketball in right now?",
      "How do I follow UIC athletics?",
      "Where can I see the UIC athletics schedule?",
      "What is Flames Fast Pass and is it worth it?",
      "Do UIC students get into games for free?",
      "How do I get student tickets for UIC games?",
      "What is the UIC athletics website?",
      "What sports are most popular at UIC?",
      "Where is the UIC recreation center?",
      "Does UIC have club sports?",
      "Does UIC have intramural sports?",
      "How do I join intramurals at UIC?",
      "How do I join club sports at UIC?",
      "Does UIC have tennis?",
      "Does UIC have soccer?",
      "Does UIC have football?",
      "What is the gym like at UIC?",
      "Can students use the rec center for free at UIC?",
      "What are the rec center hours at UIC?",
      "What fitness classes are offered at UIC?",
      "How do I stay active at UIC?",
      "What are the best sports for meeting people at UIC?",
      "What division and conference is UIC in now?",
      "Can you tell me where to follow all UIC sports online?",
      "What should a new student know about sports at UIC?",
      "Which CTA line goes to UIC?",
      "Where is the MSLC tutoring center?",
      "How does Night Ride work?",
      "Where is the Financial Aid office?",
      "How do I get from east to west campus?",
      "Where can I print on campus?",
      "How do I get to UIC by train?",
      "How do I get to UIC by bus?",
      "Where do I park at UIC?",
      "What is the best parking option at UIC?",
      "Where is Student Center East?",
      "Where is Student Center West?",
      "Where is the library at UIC?",
      "Where is the rec center at UIC?",
      "Where is the advising office for my major?",
      "Where is the registrar office at UIC?",
      "Where is the bursar office at UIC?",
      "Where is the counseling center at UIC?",
      "Where is the disability resource center at UIC?",
      "Where can I study on campus at UIC?",
      "What are the best study spots at UIC?",
      "Where are the best quiet places on campus at UIC?",
      "Where can I charge my laptop on campus at UIC?",
      "Where can I print for free at UIC?",
      "Where do I get my i-card at UIC?",
      "How do I use Night Ride at UIC?",
      "How do I get from JST to lecture center buildings?",
      "How do I get from ARC to class buildings?",
      "Where are the engineering buildings at UIC?",
      "Where are the science buildings at UIC?",
      "Where are the CS classes usually held at UIC?",
      "Where is the tutoring center for math at UIC?",
      "Where can I meet with advisors at UIC?",
      "How big is the UIC campus?",
      "Is UIC easy to get around?",
      "What is on east campus versus west campus at UIC?",
      "What is the fastest way to move around campus at UIC?",
      "Where can I eat between classes on campus?",
      "Where can I relax between classes at UIC?",
      "Where are the best commuter spaces at UIC?",
      "Can you help me understand the layout of UIC campus?",
      "Can you tell me where the most important student offices are at UIC?",
      "What are the most useful places every UIC student should know?",
      "How do I navigate campus my first week at UIC?",
      "How do I waive CampusCare insurance?",
      "Is counseling free at UIC?",
      "Where is the health clinic?",
      "How do I get disability accommodations?",
      "Where is the campus pharmacy?",
      "What does CampusCare cover at UIC?",
      "How much does CampusCare cost at UIC?",
      "How do I use CampusCare insurance?",
      "How do I make a doctor appointment at UIC?",
      "Where is the student health center at UIC?",
      "How do I get mental health support at UIC?",
      "Does UIC offer therapy for students?",
      "How do I book counseling at UIC?",
      "Is therapy confidential at UIC?",
      "How do disability accommodations work at UIC?",
      "How do I register with the disability office at UIC?",
      "Can I get testing accommodations at UIC?",
      "How do I get note taking accommodations at UIC?",
      "Can I see a doctor on campus at UIC?",
      "Can international students use the health center at UIC?",
      "Does UIC have dental services for students?",
      "Where do I go if I get sick at UIC?",
      "What if I have an emergency on campus at UIC?",
      "How do prescriptions work with CampusCare?",
      "Is there a pharmacy on campus at UIC?",
      "Can I waive student health insurance at UIC?",
      "When is the CampusCare waiver deadline?",
      "What wellness resources does UIC offer?",
      "Does UIC have stress management support?",
      "How do I talk to someone if I am overwhelmed at UIC?",
      "What health services are included in student fees at UIC?",
      "What if I need help after office hours at UIC?",
      "Can I get accommodations for anxiety or ADHD at UIC?",
      "Who should I contact for accessibility support at UIC?",
      "Can you explain CampusCare in simple terms?",
      "What health resources should every new UIC student know?",
      "What should I do first if I need accommodations at UIC?",
      "When does spring registration open?",
      "What is a registration time ticket?",
      "How do I add or drop a class?",
      "What is the last day to withdraw?",
      "How does the waitlist work at UIC?",
      "How do I handle a prerequisite override?",
      "How do I register for classes at UIC?",
      "How do time tickets work at UIC?",
      "When can freshmen register at UIC?",
      "When can transfer students register at UIC?",
      "When can graduate students register at UIC?",
      "What is open registration at UIC?",
      "How do I change my schedule after registering?",
      "How do I swap classes at UIC?",
      "What happens if a class is full at UIC?",
      "How do I get on a waitlist at UIC?",
      "What do I do if I need instructor approval for a class at UIC?",
      "How do I get a prerequisite override at UIC?",
      "How do I know if I have a hold on my account at UIC?",
      "What holds can block registration at UIC?",
      "How do I remove a registration hold at UIC?",
      "What is the deadline to drop a class without a W at UIC?",
      "What is the deadline to withdraw from a class at UIC?",
      "What happens if I drop below full time at UIC?",
      "How many credits should I take at UIC?",
      "Can I take 18 credits at UIC?",
      "How do overload approvals work at UIC?",
      "Can I add a class after the semester starts at UIC?",
      "Can I register for classes from my phone at UIC?",
      "How do I use XE Registration at UIC?",
      "What should I do before registration opens at UIC?",
      "How do I build a good schedule at UIC?",
      "Can I retake a class for grade replacement at UIC?",
      "How do repeats work at UIC?",
      "How do pass fail options work at UIC?",
      "How do I register for summer classes at UIC?",
      "How do I register for winter classes at UIC?",
      "What happens if I miss my registration time at UIC?",
      "How do I know if I am full time or part time at UIC?",
      "How do linked lectures and labs work at UIC?",
      "How do discussion sections work at UIC registration?",
      "Can you walk me through UIC registration step by step?",
      "Can you help me plan what classes to register for next semester?",
      "What should a freshman know about registering at UIC?",
      "What is the UIC application deadline?",
      "Does UIC require SAT or ACT?",
      "What is the transfer GPA requirement?",
      "What is the Guaranteed Admission Transfer?",
      "What happens after I'm accepted?",
      "When does housing open for admitted students?",
      "What GPA do I need to get into UIC?",
      "How hard is it to get into UIC?",
      "Is UIC test optional?",
      "What documents do I need to apply to UIC?",
      "When should I apply to UIC?",
      "How do I apply to UIC as a freshman?",
      "How do I apply to UIC as a transfer student?",
      "How do I apply to UIC as an international student?",
      "What happens after I get admitted to UIC?",
      "How do I accept my UIC admission offer?",
      "How do I send transcripts to UIC?",
      "Does UIC superscore ACT or SAT?",
      "What majors are hardest to get into at UIC?",
      "Can I change my major after applying to UIC?",
      "What is the application fee for UIC?",
      "What are the admission requirements for engineering at UIC?",
      "What are the admission requirements for CS at UIC?",
      "What are the admission requirements for nursing at UIC?",
      "What are the admission requirements for business at UIC?",
      "How does guaranteed transfer admission work at UIC?",
      "What is the difference between freshman and transfer admission at UIC?",
      "When should transfer students apply to UIC?",
      "When should international students apply to UIC?",
      "Does UIC accept dual credit and AP credit for admission?",
      "What should I do after getting accepted to UIC?",
      "When do admitted students sign up for orientation at UIC?",
      "When do admitted students pick housing at UIC?",
      "How do I submit vaccination records after admission to UIC?",
      "What is the next step after paying my deposit to UIC?",
      "How do I know if I got scholarships after admission to UIC?",
      "What should parents know about the UIC admissions process?",
      "How competitive is UIC for out of state students?",
      "How competitive is UIC for international students?",
      "Can you explain the UIC admissions process step by step?",
      "Can you help me understand what happens after I am accepted to UIC?",
      "What is the smartest timeline for applying to UIC?",
      "What should I do first if I want to apply to UIC?",
      "How do I find internships as a UIC student?",
      "Where is the Career Services office?",
      "Can F-1 students work on campus?",
      "How do I get a graduate assistantship?",
      "How does Handshake work at UIC?",
      "How do I get an internship through UIC?",
      "What career resources does UIC offer?",
      "How do I book a resume review at UIC?",
      "How do I get help with LinkedIn at UIC?",
      "How do I prepare for the UIC career fair?",
      "What employers recruit at UIC?",
      "Which majors at UIC get the best internships?",
      "How do I find on campus jobs at UIC?",
      "Where do I apply for student jobs at UIC?",
      "How do I get research opportunities at UIC?",
      "How do I get a TA or GA position at UIC?",
      "How do I use Handshake as a UIC student?",
      "What should I put on my resume as a freshman at UIC?",
      "How do I get experience if I have no internships yet at UIC?",
      "What are the best career fairs at UIC?",
      "How do I find internships in Chicago while at UIC?",
      "How do I network better at UIC?",
      "What career clubs should I join at UIC?",
      "What is the best time to look for internships at UIC?",
      "How early should freshmen start career prep at UIC?",
      "Can commuters still use career services at UIC?",
      "Can transfer students use career services at UIC?",
      "What career help does UIC offer for international students?",
      "How do I get interview practice at UIC?",
      "Does UIC help students find jobs after graduation?",
      "How do I get a part time job on campus at UIC?",
      "How do I get a summer internship from UIC connections?",
      "What career resources are best for freshmen at UIC?",
      "What career resources are best for seniors at UIC?",
      "How do I build a strong resume while studying at UIC?",
      "What should CS majors do early at UIC for career success?",
      "What should business majors do early at UIC for career success?",
      "Can you help me build a career plan while at UIC?",
      "Can you explain all the main UIC career resources to me?",
      "What should every new UIC student know about jobs and internships?",
      "How can I use UIC to maximize my career opportunities?",
      "What do I need to do as a new F-1 student?",
      "How does CPT work at UIC?",
      "What is OPT and when can I apply?",
      "Do I need to check in with OIS?",
      "Can I work on campus as an F-1 student?",
      "How do I get a travel signature?",
      "What should international students do first at UIC?",
      "How do I maintain F-1 status at UIC?",
      "What is OIS at UIC?",
      "How do I contact OIS at UIC?",
      "How do I check in as a new international student at UIC?",
      "How do I get my I-20 from UIC?",
      "How do I transfer my SEVIS record to UIC?",
      "What documents do international students need for UIC?",
      "How do international students register for classes at UIC?",
      "How many credits do F-1 students need at UIC?",
      "Can international students work on campus at UIC?",
      "How do I apply for CPT at UIC?",
      "How do I apply for OPT at UIC?",
      "When should I apply for OPT through UIC?",
      "Can I do internships as an international student at UIC?",
      "What jobs can international students do at UIC?",
      "How do reduced course loads work for international students at UIC?",
      "What happens if I drop below full time as an F-1 student at UIC?",
      "How do I get a travel signature from UIC?",
      "How long is a travel signature valid at UIC?",
      "What should I carry when re entering the US as a UIC student?",
      "Can international students live off campus at UIC?",
      "Do international students get scholarships at UIC?",
      "How do health insurance rules work for international students at UIC?",
      "How do I update my address as an F-1 student at UIC?",
      "Can international students change majors at UIC?",
      "Can international students work off campus at UIC?",
      "What is the difference between CPT and OPT at UIC?",
      "How do I renew my I-20 at UIC?",
      "How do I get help from OIS quickly at UIC?",
      "How do I know if I am maintaining valid status at UIC?",
      "Can I take online classes as an international student at UIC?",
      "What should new international freshmen know at UIC?",
      "What should new international transfers know at UIC?",
      "Can you explain CPT and OPT in simple words for UIC students?",
      "Can you explain the first semester checklist for an international student at UIC?",
      "What should I do before traveling outside the US as a UIC international student?",
      "What are the most important rules for F-1 students at UIC?",
      "What is the full international student setup process at UIC?",
      "How does the safety escort work?",
      "What is the UIC Safe app?",
      "How do I report a bias incident?",
      "Who do I contact for a campus emergency?",
      "Are student legal services free?",
      "What is Title IX at UIC?",
      "What safety resources does UIC offer students?",
      "How do I use Night Ride at UIC?",
      "What is the safety escort service at UIC?",
      "How do I contact campus police at UIC?",
      "What is the emergency number for UIC?",
      "How do I report suspicious activity at UIC?",
      "How do I report harassment at UIC?",
      "How do I report sexual misconduct at UIC?",
      "How do I report discrimination at UIC?",
      "What should I do in a campus emergency at UIC?",
      "How do campus emergency alerts work at UIC?",
      "How do I sign up for safety alerts at UIC?",
      "What does the UIC Safe app do?",
      "Does UIC have blue light emergency phones?",
      "Where can I find campus police at UIC?",
      "How do I stay safe as a commuter at UIC?",
      "How do I stay safe walking home from UIC?",
      "How do I stay safe on public transit to UIC?",
      "What should freshmen know about safety at UIC?",
      "What should students living in dorms know about safety at UIC?",
      "What should students living off campus know about safety near UIC?",
      "What is Title IX and how does it help students at UIC?",
      "How do no contact orders work at UIC?",
      "Are there legal services for students at UIC?",
      "How do I get help if I feel unsafe at UIC?",
      "How do I report a bias incident at UIC?",
      "How do I get confidential support after an incident at UIC?",
      "What safety services are open late at UIC?",
      "Can I request an escort at night at UIC?",
      "What are the biggest safety tips for new UIC students?",
      "What resources help students in crisis at UIC?",
      "Where do I go for legal help as a UIC student?",
      "Can you explain all the main UIC safety resources?",
      "Can you tell me what to do step by step in an emergency at UIC?",
      "What should every student save in their phone for UIC safety?",
      "What are the most important student protections at UIC?",
      "What should I know about staying safe at UIC from day one?",
      
];

export default function HeroSearchBar() {
  const [displayed, setDisplayed] = useState("");
  const [phraseIndex, setPhraseIndex] = useState(0);
  const [charIndex, setCharIndex] = useState(0);
  const [deleting, setDeleting] = useState(false);
  const [paused, setPaused] = useState(false);

  useEffect(() => {
    if (paused) {
      const t = setTimeout(() => { setPaused(false); setDeleting(true); }, 1800);
      return () => clearTimeout(t);
    }

    const current = PHRASES[phraseIndex];

    if (!deleting) {
      if (charIndex < current.length) {
        const t = setTimeout(() => {
          setDisplayed(current.slice(0, charIndex + 1));
          setCharIndex(c => c + 1);
        }, 38);
        return () => clearTimeout(t);
      } else {
        setPaused(true);
      }
    } else {
      if (charIndex > 0) {
        const t = setTimeout(() => {
          setDisplayed(current.slice(0, charIndex - 1));
          setCharIndex(c => c - 1);
        }, 18);
        return () => clearTimeout(t);
      } else {
        setDeleting(false);
        setPhraseIndex(i => (i + 1) % PHRASES.length);
      }
    }
  }, [charIndex, deleting, paused, phraseIndex]);

  return (
    <div className="max-w-2xl mx-auto mb-6">
      <Link href="/chat" className="group block w-full">
        <div className="flex items-center gap-3 bg-zinc-900 border border-zinc-700 rounded-xl px-5 py-4 hover:border-red-500 transition-colors cursor-text">
          <img src="/sparky-icon.png" alt="Sparky" className="w-7 h-7 object-contain" />
          <span className="flex-1 text-sm text-zinc-500 text-left min-w-0">
            {displayed
              ? <span className="text-zinc-300">{displayed}<span className="inline-block w-0.5 h-3.5 bg-red-500 ml-0.5 align-middle animate-pulse" /></span>
              : <span className="italic">Ask Sparky anything...</span>
            }
          </span>
          <span className="bg-red-600 group-hover:bg-red-500 text-white font-bold px-4 py-2 rounded-lg text-sm transition-colors whitespace-nowrap shrink-0">
            Ask Sparky →
          </span>
        </div>
      </Link>
    </div>
  );
}